In [155]:
from google.colab import files
uploaded=files.upload()

Saving marks.csv to marks (4).csv


In [156]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [157]:
df=pd.read_csv('marks.csv')
df


Student   math  stats
0         A    95     85
1         B    85     95
2         C    80     70
3         D    70     65
4         E    60     70
5         F    62     75
6         G    81     84
7         H    64     72
8         I    57     68
9         J    49     61
10        K    43     54
11        L    82     93
12        M    91     80
13        N    55     68

In [158]:

x=df['math']
y=df['stats']


In [159]:
x

0     95
1     85
2     80
3     70
4     60
5     62
6     81
7     64
8     57
9     49
10    43
11    82
12    91
13    55
Name: math, dtype: int64

In [160]:
y

0     85
1     95
2     70
3     65
4     70
5     75
6     84
7     72
8     68
9     61
10    54
11    93
12    80
13    68
Name: stats, dtype: int64

In [161]:
sum_x=np.sum(x)
sum_x

974

In [162]:
sum_y=np.sum(y)
sum_y

1040

In [163]:
mean_x=np.mean(x)
mean_x

69.57142857142857

In [164]:
mean_y=np.mean(y)
mean_y

74.28571428571429

In [165]:
xix=np.array(x-mean_x)
xix

array([ 25.42857143,  15.42857143,  10.42857143,   0.42857143,
        -9.57142857,  -7.57142857,  11.42857143,  -5.57142857,
       -12.57142857, -20.57142857, -26.57142857,  12.42857143,
        21.42857143, -14.57142857])

In [166]:
yiy=np.array(y-mean_y)
yiy

array([ 10.71428571,  20.71428571,  -4.28571429,  -9.28571429,
        -4.28571429,   0.71428571,   9.71428571,  -2.28571429,
        -6.28571429, -13.28571429, -20.28571429,  18.71428571,
         5.71428571,  -6.28571429])

In [167]:
xy=np.array(xix*yiy)
xy

array([272.44897959, 319.59183673, -44.69387755,  -3.97959184,
        41.02040816,  -5.40816327, 111.02040816,  12.73469388,
        79.02040816, 273.30612245, 539.02040816, 232.59183673,
       122.44897959,  91.59183673])

In [168]:
sum_xy=np.sum(xy)
sum_xy

2040.7142857142856

In [169]:
xy_sub=np.square(x-mean_x)
xy_sub

0     646.612245
1     238.040816
2     108.755102
3       0.183673
4      91.612245
5      57.326531
6     130.612245
7      31.040816
8     158.040816
9     423.183673
10    706.040816
11    154.469388
12    459.183673
13    212.326531
Name: math, dtype: float64

In [170]:
sum_xysub=np.sum(xy_sub)
sum_xysub

3417.4285714285716

In [171]:
b1=sum_xy/sum_xysub
b1

0.5971490678036953

In [172]:
b0=mean_y-(mean_x*b1)
b0

32.74120056851435

In [173]:
pred=b0+b1*55
pred

65.5843992977176

In [174]:
from sklearn.linear_model import LinearRegression

In [175]:
lm=LinearRegression()

In [176]:
x=df[['math']]
y=df['stats']

In [177]:
lm.fit(x,y)

LinearRegression()

In [178]:
lm.intercept_

32.741200568514344

In [179]:
lm.coef_

array([0.59714907])

In [180]:
yhat=lm.predict(x)
yhat


array([89.47036201, 83.49887133, 80.51312599, 74.54163531, 68.57014464,
       69.76444277, 81.11027506, 70.95874091, 66.77869743, 62.00150489,
       58.41861048, 81.70742413, 87.08176574, 65.5843993 ])

In [181]:
#finding mean squared error without using the packages
x1=df['math']
x2=df['stats']
mse=(1/14)*(np.square(y-yhat))
mse

0     1.427438
1     9.448283
2     7.894701
3     6.503057
4     0.146035
5     1.957933
6     0.596465
7     0.077444
8     0.106541
9     0.071644
10    1.394580
11    9.108734
12    3.582243
13    0.416795
Name: stats, dtype: float64

In [182]:
a_mse=np.sum(mse)
a_mse

42.73189353494096

In [183]:
#finding mse using packages
from sklearn.metrics import mean_squared_error

In [184]:
m_se=mean_squared_error(y,yhat)


In [185]:
m_se

42.73189353494097